# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-10 01:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JsonData',
            fields=[
                ('version', models.CharField(max_length=16)),
                ('arch', models.CharField(max_length=8)),
                ('product', models.CharField(max_length=16)),
                ('operatingSystem', models.CharField(max_length=64)),
                ('gms_ip', models.CharField(max_length=16)),
                ('testname', models.CharField(max_length=64)),
                ('filepath', models.CharField(max_length=300, primary_key=True, serialize=False)),
                ('time', models.DateTimeField()),
            ],
        ),
    ]
